# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-10 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('addr', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': '\u6821\u533a',
            },
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.SmallIntegerField(choices=[(0, '\u9762\u6388\uff08\u8131\u4ea7\uff09'), (1, '\u9762\u6388\uff08\u5468\u672b\uff09'), (2, '\u7f51\u7edc\u73ed')], verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='\u5b66\u671f')),
                ('start_date', models.DateTimeField(verbose_name='\u5f00\u73ed\u65e5\u671f')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u4e1a\u65e5\u671f')),
                ('brance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Branch', verbose_name='\u6821\u533a')),
            ],
            options={
                'verbose_name_plural': '\u73ed\u7ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.PositiveSmallIntegerField(verbose_name='\u8bfe\u7a0b\u4ef7\u683c')),
                ('period', models.PositiveSmallIntegerField(verbose_name='\u5468\u671f\uff08\u6708\uff09')),
                ('outline', models.TextField(verbose_name='\u8bfe\u7a0b\u5927\u7eb2')),
            ],
            options={
                'verbose_name_plural': '\u8bfe\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.PositiveSmallIntegerField(verbose_name='\u7b2c\u51e0\u8282')),
                ('has_homework', models.BooleanField(default=True)),
                ('homework_title', models.CharField(blank=True, max_length=128, null=True)),
                ('homework_content', models.TextField(blank=True, null=True)),
                ('outline', models.TextField(verbose_name='\u672c\u8282\u8bfe\u7a0b\u5927\u7eb2')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='\u73ed\u7ea7')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u4e0a\u8bfe\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('qq', models.CharField(max_length=64, unique=True)),
                ('qq_name', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.SmallIntegerField(choices=[(0, '\u8f6c\u4ecb\u7ecd'), (1, 'QQ\u7fa4'), (2, '\u5b98\u7f51'), (3, '\u767e\u5ea6\u63a8\u5e7f'), (4, '51CTO'), (5, '\u77e5\u4e4e'), (6, '\u5e02\u573a\u63a8\u5e7f')])),
                ('referral_from', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8f6c\u4ecb\u7ecd\u4ebaqq')),
                ('content', models.TextField(verbose_name='\u54a8\u8be2\u8be6\u60c5')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consult_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Course', verbose_name='\u54a8\u8be2\u8bfe\u7a0b')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u9500\u552e\u987e\u95ee')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8ddf\u8fdb\u5185\u5bb9')),
                ('intention', models.SmallIntegerField(choices=[(0, '2\u5468\u5185\u62a5\u540d'), (1, '1\u4e2a\u6708\u5185\u62a5\u540d'), (2, '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), (3, '\u5df2\u5728\u5176\u4ed6\u673a\u6784\u62a5\u540d'), (4, '\u5df2\u62a5\u540d'), (5, '\u5df2\u62c9\u9ed1')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8ddf\u8fdb\u4eba')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer')),
            ],
            options={
                'verbose_name_plural': '\u5ba2\u6237\u8ddf\u8e2a\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_agreed', models.BooleanField(default=False, verbose_name='\u5b66\u5458\u5df2\u540c\u610f\u5408\u540c')),
                ('contract_approved', models.BooleanField(default=False, verbose_name='\u5408\u540c\u5df2\u5ba1\u6838')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bfe\u7a0b\u987e\u95ee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer')),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='\u6240\u62a5\u73ed\u7ea7')),
            ],
            options={
                'verbose_name_plural': '\u62a5\u540d\u8868',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_type', models.SmallIntegerField(choices=[(0, 'alias'), (1, 'absolute_url')], default=0)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '\u83dc\u5355\u8868',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=500, verbose_name='\u6570\u989d')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer')),
            ],
            options={
                'verbose_name_plural': '\u7f34\u8d39\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('menus', models.ManyToManyField(blank=True, to='app01.Menu')),
            ],
            options={
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.SmallIntegerField(choices=[(0, '\u5df2\u7b7e\u5230'), (1, '\u8fdf\u5230'), (2, '\u7f3a\u52e4'), (3, '\u65e9\u9000')], default=0)),
                ('score', models.SmallIntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (75, 'B-'), (70, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (-100, 'COPY'), (0, 'N/A')], default=0)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.CourseRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Enrollment')),
            ],
            options={
                'verbose_name_plural': '\u5b66\u4e60\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': '\u6807\u7b7e\u8868',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Tag'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Course'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([('student', 'course_record')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('customer', 'enrolled_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together=set([('from_class', 'day_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('brance', 'course', 'semester')]),
        ),
    ]
