# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180211_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app01.Role'),
        ),
    ]
