# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u5e38\u7528\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '\u672a\u62a5\u540d'), (1, '\u5df2\u62a5\u540d')], default=0),
        ),
    ]
