# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_fuck_him_to_death', '\u5f04\u6b7b\u4f60'), ('can_access_my_course', '\u53ef\u4ee5\u67e5\u770b\u6211\u7684\u8bfe\u7a0b'), ('can_access_customer_list', '\u53ef\u4ee5\u67e5\u770b\u5ba2\u6237\u5217\u8868'), ('can_access_customer_detail', '\u53ef\u4ee5\u67e5\u770b\u5ba2\u6237\u8be6\u7ec6\u4fe1\u606f'), ('can_upload_homework', '\u53ef\u4ee5\u4ea4\u4f5c\u4e1a'))},
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8(\u8bc4\u8bed)'),
        ),
    ]
